openapi: 3.0.3
info:
  title: Product & Order API
  version: "1.0.0"
tags:
  - name: Products
    description: Product's endpoints
  - name: Orders
    description: Orders endpoints
paths:
  /products:
    get:
      tags:
        - Products
      summary: List of products
      description: Return the list of available products
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        200:
          description: List of products successfully found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                successExample:
                  summary: Example of products
                  value:
                    - id: 1
                      name: Phone
                      price: 1200.55
                    - id: 2
                      name: Mouse
                      price: 10.00

  /orders:
    get:
      tags:
        - Orders
      summary: List customer orders
      description: Return the list of orders
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/size'
      responses:
        200:
          description: List of orders successfully found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
              examples:
                successfulExample:
                  summary: Example of orders
                  value:
                    - id: 101
                      customer_name: Fiononantsoa
                      creation_datetime: "2023-12-01T12:34:25Z"
                      total_amount: 115.24
                    - id: 202
                      customer_name: Alice
                      creation_datetime: "2023-04-23T14:58:41Z"
                      total_amount: 888.66
    post:
      tags:
        - Orders
      summary: Create order
      description: Create a new order (requires basic authentication)
      security:
        - basicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              orderExample:
                summary: Example request
                value:
                  customer_name: Charls
                  creation_datetime: "2025-12-04T14:58:36Z"
                  total_amount: 44.55
      responses:
        201:
          description: Order successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                createOrderExample:
                  summary: Example response
                  value:
                    id: 203
                    customer_name: Karl
                    creation_datetime: "2024-12-28T22:25:56Z"
                    total_amount: 11.55
        401:
          description: Unauthorized â€“ authentication required

components:
  parameters:
    page:
      in: query
      name: page
      required: true
      schema:
        type: integer
        default: 1
      description: Page number for pagination
    size:
      in: query
      name: size
      required: false
      schema:
        type: integer
        default: 10
      description: Number of elements per page
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: Laptop
        price:
          type: number
          format: float
          example: 32.66
      required:
        - id
        - name
        - price
    Order:
      type: object
      properties:
        id:
          type: integer
          example: 1
        customer_name:
          type: string
          example: Mark
        creation_datetime:
          type: string
          format: date-time
          example: "2024-12-25T14:20:36Z"
        total_amount:
          type: number
          format: float
          example: 1999.66
      required:
        - customer_name
        - creation_datetime
        - total_amount
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
